// Generated by Wrangler by running `wrangler types`

interface Env {
	NEWT_SPACE_UID: string
	NEWT_CDN_API_TOKEN: string
	NEWT_APP_UID: string
	POSTMARK_API_TOKEN: string
	TURNSTILE_SITE_KEY: string
	TURNSTILE_SECRET_KEY: string
	R2: R2Bucket
}
