// Generated by Wrangler by running `wrangler types`

interface Env {
	NEWT_SPACE_UID: string
	NEWT_CDN_API_TOKEN: string
	NEWT_APP_UID: string
	GOOGLE_SHEET_KEY: string
	GOOGLE_SHEET_NAME: string
	GOOGLE_SHEET_ID: string
	R2: R2Bucket
}
